# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO_ENABLED=0 for static binary, GOOS/GOARCH set automatically by Buildx
RUN CGO_ENABLED=0 go build -o songswap ./cmd/api/main.go

# Stage 2: Run
FROM alpine:3.20

WORKDIR /app
COPY --from=builder /app/songswap .

EXPOSE 8080
CMD ["./songswap"]